### ISSUE TITLE
I am trying to finish this tutorials

### ISSUE THREAD

**Issue by Kuanch** [Kuanch/office_hour#1]
@ching9752   
嗨

**Comment by ching9752** [comment]
這是什麼神奇的東東!!!

**Comment by Kuanch** [comment]
像是工程師的無名小站 XDDDD

一般來說 issues 會用在
1. 有明顯 Bug
2. 對程式碼有疑問
3. 求開發新功能

在像是 Google 或微軟臉書那些很大很肥很多星星的 repo 中，也是很多寶藏的地方

**Comment by ching9752** [comment]
欸我有很多事要跟你說 跟山一樣多😂😂😂
但我如果在這邊問太蠢太凡間的問題會不會拉低你的GitHub格調哈哈哈哈哈

乾你怎麼知道我是收到信來看的😳

我明天把作業資料連結給你，然後我下禮拜會開始寫GMM～～～
其實我這幾天已經讀完上課內容ㄌ但我感覺它跟作業是兩個世界，到底為什麼老師要給我已經分類好的圖片QQ

**Comment by Kuanch** [comment]
我們不是上禮拜剛見嗎哈哈哈哈
這裡就是給你回報問題的啊，盡量說
你要用 LINE 或 discord 也都可以

因為你回的時候我也有收到信 XDDD

你給星星的那一個 repo 感覺蠻靠譜的，值得試試看
分類好的圖片是讓你對答案的吧？

**Comment by ching9752** [comment]
被你發現我在偷偷看別人的code哈哈哈哈 而且我還沒有看懂QQ
我現在就是濟公，code穿腸過、問號心頭坐XDDD

那幾件事跟你縮：
1. 我初步隨機想出來的碩論方向是辨識紅綠燈的秒數，不知道可不可行，還要問老師（？？？
2. 期末農作物辨識的模型，博班學弟把我拎過去跟他一組了，用的是EfficientNet
3. 承上，我被分配到幾個小任務（Confusion matrix/cross function/data argumentation )預計下禮拜要來做，應該會有爆炸多問題要問你，但我還沒有時間開始處理這些事
4. GMM我真的沒看懂為何能拿來作Clustering，他的原理我懂，但我沒懂用多個高斯逼近原始的曲線之後為什麼能做Clustering，等我下禮拜看一下別人的程式碼和解說再來問你QQ
5. Pytorch如果我下禮拜作業都搞定了會開始看，因為要建模了XDDDD
6. GMM作業連結 https://drive.google.com/drive/u/0/folders/1SgW77YDrpjCB9PmQshRVR7Hdllikz4Qt

這個禮拜的進度大概4這樣，我這週末要預支快樂沒有辦法有為國家貢獻哈哈哈哈哈
我拖著全部的人要去看羊羊！！！！！！！

**Comment by Kuanch** [comment]
1. 好像不錯，感覺可以擴展成號誌辨識
2. 讚，那你幫我確定一下他是不是有偏好什麼工具，如 Tensorflow or Keras or Pytorch ，他在那邊比較好跟你討論東西，就照他的走
3. 這幾個都沒問題，但承上，我跟他的工具同步會比較好
4. 我還沒看哈哈哈哈，這周來看
5. pytorch 有可以很快呼叫 EfficientNet 的方式，如果用 pytorch 應該會頗快
6. 權限 QQ

恭喜你又過了學期中的一個禮拜，還拿到實習面試，辛苦了，你好棒！
把羊玩爆

**Comment by ching9752** [comment]
我在讀Pytorch的Tutorial中遇到了幾個問題～
出來冒個泡泡問問看助教>___<

1. resnet50(pretrained=False)中pretrained=False是代表什麼意思
第一篇有寫True是直接引入原本的 ImageNet pretrained model，那pretrained=False是不遷移學習就從零開始嗎？

2. !wget 不能用
不知道我的虛擬環境被我怎麼了XD 總之就是!會被報錯，我網路查了一下改成這樣（所以這個其實不用解決沒關係XDD)
import wget
url = 'https://raw.githubusercontent.com/EliSchwartz/imagenet-sample-images/master/n02085936_Maltese_dog.JPEG'
file_name = wget.download(url)
print(file_name)

3. get clone失敗
我查了要用terminal後丟了git clone 之後就卡在黑黑的畫面，不知道該怎麼辦了OvO
(所以我現在都慢慢一個cell複製）

4. 當我打開Jupiter notebook後的終端機頁面就沒有(ching) C:\Users\MAGIC>，我就迷失在黑底白字中了，我要如何回到正常畫面C:\Users\MAGIC>（因為想要pip install)
我現在的做法是不管他，全部關掉重開XDDDDDDDDDDDD

6. 引入狗狗圖片的時候 img = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)，為什麼你知道狗狗的圖片現在是BGR（我都不知道QQ)然後為什麼順序是轉成RGB，這是默認的規定嗎？

7. 
img = img / 127.5
img = img - 1 中的127.5是怎麼來的，以及img = img - 1 是什麼意思QQ

好了我暫時就讀到這個cell就卡住惹，偷看了一下下面覺得不太懂XDDDDDDD
這週會努力繼續推進度的！！
助教上班加油！好好賺錢！！！！
